# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('car', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_place', models.TextField(max_length=100)),
                ('arrival_place', models.TextField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reccomended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalScore', models.FloatField()),
                ('driver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blablaPro.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='TripsDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_place', models.TextField(max_length=100)),
                ('arrival_place', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.TextField()),
                ('driver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blablaPro.Driver')),
            ],
        ),
    ]
